### ISSUE TITLE
Handling fragmented/partial genes

### ISSUE THREAD

**Issue by adityabandla** [AstrobioMike/GToTree#10]
How does GToTree currently handle the issue of partial genes? 
What is the minimum aligned fraction % value during the hmm step?

**Comment by AstrobioMike** [comment]
Hi there, Aditya,

Thanks for writing in. 

There is no explicit % alignment fraction minimum threshold in the HMM searching, but the HMM searching is handled with what’s called a gathering threshold cutoff. This is turned on with the `--cut-ga` flag, and it employs bitscore cutoffs that are unique to each individual HMM profile. These are empirically derived and manually curated by Pfam to limit false positives. So it’s not as straightforward as having a single minimum alignment fraction, but rather it’s a give and take between that and similarity, and the minimum allowable score comes from what all the trusted things look like to that HMM profile, while not allowing any known false positives through. 

That would likely stop any partials from getting through to the alignment step, but then GToTree also employs a [length-based gene-filtering step](https://github.com/AstrobioMike/GToTree/wiki/user-guide#filtering-gene-hits-by-length) before alignment based on the median length of the identified genes for each given target. 

Does that answer your question?

**Comment by adityabandla** [comment]
Thanks Mike, yes, its clear to me now
I assume that --cut_ga takes care cases where multiple domains hit the same sequence region?

**Comment by AstrobioMike** [comment]
Hmm, so there are a couple ways I can think of what might be meant there, so i'll try to hit the interpretations I can think of and let me know if none of them are actually responding to how you do mean it, ha

First, i'd note that in creating the SCG-sets used in GToTree (except the Hug universal set), I filtered out Pfams that didn't cover more than half of the underlying source proteins to lesson the chance (drastically) that any given protein would have hits to more than one Pfam (e.g. from [here](https://github.com/AstrobioMike/GToTree/wiki/SCG-sets)):

>1. All 17,929 Pfams from release 32.0 were downloaded. Those that didn’t cover more than 50% (on average) of the underlying protein sequences that went into building that Pfam's HMM were filtered out (this ensures there would be no two Pfams from the same source protein included). This left 8,924 Pfams.

And there can be a case where more than one protein hits to the same Pfam (i.e. multiple copies in a genome), and in those cases GToTree by default takes the conservative route and doesn't include any of those hits (though you can change that [behavior](https://github.com/AstrobioMike/GToTree/wiki/user-guide#best-hit-mode).
 
Beyond that I don't think there will often be a case where multiple different HMMs hit to the same protein, as the manually curated Pfams are conservatively designed to have those gathering thresholds such that they don't allow any false positives of known things. That doesn't in practice mean the "wrong" protein can't have a successful hit when it shouldn't, but i do think it means it'd be highly unlikely for the same protein to cross those thresholds for more than one HMM. 

Please do let me know if i'm not following you or making any sense :)
