### ISSUE TITLE
../gtt-fasta-serial.sh: line 144: esl-sfetch: command not found

### ISSUE THREAD

**Issue by Irrussional** [AstrobioMike/GToTree#13]
Hey Mike, I believe I'm having trouble with one of the HMM modules, but i'm not entirely sure. The error is `../gtt-fasta-serial.sh: line 144: esl-sfetch: command not found`

It practically fails the first step of drawing HMMs if I understand correct. 
I am running analyses on a cluster with HMMer installed, and I don't have any kind of install rights, so I am trying figure out whether the HMMer's `esl-fetch` is damaged or something like that. I tried to install HMMer locally, but I am not sure whether when I call GToTree it can actually draw from the local installation. As you can already imagine, I am quite new to bash : ) Any hints are very welcome!

**Comment by AstrobioMike** [comment]
Hi there, @Irrussional!

I didn’t highlight this as much as I should have on the [installing dependencies without conda](https://github.com/AstrobioMike/GToTree/wiki/installation#installing-dependencies-without-conda) section (as I only have it in parentheses in the first paragraph and not in the list for some silly reason, ill fix that, ha), but there is another program called Easel that comes with HMMER, but isn’t installed at the same time (if not installing HMMER with conda). That’s where the `esl-` commands come from :)

Im not sure if the setup you’re working on will be able to find your local programs either, but you can try finishing the Easel installation and see if that helps first. There is some more info on that at the [HMMER installation page here](http://hmmer.org/documentation.html). And they note:

> The 'make install' in Easel installs a set of other small tools and their man pages. We don't make this part of the HMMER 'make install' because Easel is part of other packages (Infernal, for example) and you might have already installed Easel tools.

If that doesn’t help, then I think you need to ask whoever does handle installs on the cluster to also install Easel. Or if possible, to install GToTree with conda, as conda Just makes the world a better place, haha

Sorry for the complications! I hope this helps!

**Comment by Irrussional** [comment]
Thanks for the clarifications! Actually I just installed it with conda on a local machine and now it works! Should have tried it in the first place, compiling in a foreign cluster / machine is always problematic..
I do have another practical problem though: I'm working with a few Chlamydial MAGs which I wanted to simply put in a phylogenomic tree, for that I retrieved everything Chlamydiae-related from NCBI and ran GToTree with -H Chlamydiae, but almost 20 MAGs/genomes recognized in NCBI as chlamydial were removed due to too few hits. Is there a way to flag them for being kept (and obviously have some kind of notion that there were too few hits?).
Also if you want, I can create another "issue" since this is a different discussion now.
Cheers!
Artur

**Comment by AstrobioMike** [comment]
Ah great! 

Regarding part of your initial message about the Chlamydiae (that’s what my email showed, ha), you can alter the `-G` [parameter](https://github.com/AstrobioMike/GToTree/wiki/user-guide#filtering-genomes-based-on-hits-to-target-genes), which says how many need to be found for the genome to be kept. It’s 0.5 by default. 

Cheers!

**Comment by Irrussional** [comment]
Hey, Mike, thanks a lot! I indeed missed on the -G option earlier, but then was able to find it after posting the message, so I later just edited it to remove the question. Thanks!

Artur
