### ISSUE TITLE
-m mapping file does not work with full path

### ISSUE THREAD

**Issue by vinisalazar** [AstrobioMike/GToTree#14]
Hey @AstrobioMike,

once again thanks for providing this package. I noticed a small bug when using the -m parameter. I usually provide my files with the full (absolute path) as input. However, if I use the full path in the first column of the -m mapping file, it doesn't match and I get "Missing IDs".

That was easily fixed by simply providing the file names (instead of the absolute path) in the first column of the mapping file. However, I thought it would be useful to report this in case other users came across the same problem. Maybe this error could raise an Exception?

Thank you for any assistance you can provide,

V

**Comment by AstrobioMike** [comment]
Ah, thanks, @vinisalazar! I very much appreciate you writing in about it even though you found a workaround. I will definitely implement something to either deal with this properly, or give an actually useful message like you suggest as soon as possible.

Thanks again :)

**Comment by vinisalazar** [comment]
Thanks for the quick reply.

Just noticed one more thing. When I ran the workflow with only the filenames (no absolute paths) in the -m file, it seemed to run fine. But, it has just finished and the .tre file was empty. All other files seem fine (e.g. Aligned_SCGs_mod_names.faa was ok, with the correct labels in the FASTA headers). I ran it a second it without passing the -m parameter and the .tre file was generated correctly.

So I suspect something might be going on with this -m parameter in the tree building step.

Best,

V

**Comment by AstrobioMike** [comment]
Hmm, i can't seem to recreate the problem when just providing the base file name. If you are using a conda installation, can you see if you get the same problem if you run the `gtt-test.sh` command? 

The test mapping file there looks like this (so we can see the columns clearly):
![image](https://user-images.githubusercontent.com/13923308/77371872-87ec9a80-6d21-11ea-81bd-567f6592bc5c.png)
(it will print out where your test files are located when you run `gtt-test.sh` in the `gtotree` conda environment)

And then looking at that tree the labels are changed appropriately: 
![image](https://user-images.githubusercontent.com/13923308/77371952-c08c7400-6d21-11ea-8182-6d71a213f54e.png)

Can you let me know if that `gtt-test.sh` fails for you the same way or if it works for you like it does for me?

**Comment by AstrobioMike** [comment]
Got the first thing fixed from v1.4.12 on, the conda installs are up-to-date for it 👍 

Let me know if you still have a problem running it either way when you get to it again, please :) 

And thanks again!

**Comment by vinisalazar** [comment]
Thank you for the instructions, I wasn't aware there was a test command. Tomorrow I will update GTT and report back.

Best,
V

**Comment by vinisalazar** [comment]
Hi @AstrobioMike , I updated the conda install, the test command ran fine, and I figured out that the tree failing to build was an error on my end (duplicate labels). So all is good. Thank you for your help.

Best,
V

**Comment by AstrobioMike** [comment]
Ah, kind of you, but we can do better than failing with no info when that happens, ha. I’ll look into that! Thanks!

**Comment by vinisalazar** [comment]
I've been getting this duplicate label error often, so I made a quick PR to try to fix it, hope you find it useful :)

**Comment by AstrobioMike** [comment]
your check is in as of 1.4.13! now the latest conda version installed, thanks again!

**Comment by vinisalazar** [comment]
You're welcome! Happy to be (apparently) the first contributor! I've been using this a lot, and recently submitted a couple papers using/citing it. It's a game changer for sure.

**Comment by AstrobioMike** [comment]
Awesome! Thanks! I meant to mention you were the first, big day for GToTree!
