### ISSUE TITLE
Whether the software has the ability to run offline？

### ISSUE THREAD

**Issue by panxiaoguang** [AstrobioMike/GToTree#16]

**Comment by AstrobioMike** [comment]
Hi there, it will work just fine if we are providing all the input genomes. But if we want to pull genomes from NCBI based on their accession, we need to be online. Does that make sense?

**Comment by panxiaoguang** [comment]
> Hi there, it will work just fine if we are providing all the input genomes. But if we want to pull genomes from NCBI based on their accession, we need to be online. Does that make sense?

I would also like to do evolutionary analysis by accession, but since compute servers are usually intranet, is there a tutorial that separates the two processes of accession to obtain sequences and compute evolutionary relationships for non-networked servers

**Comment by AstrobioMike** [comment]
I don’t have a tutorial up for that, but I do have the script that downloads things from ncbi in GToTree by itself in my [bioinformatics toolkit](https://github.com/AstrobioMike/bioinf_tools/blob/master/README.md#bioinformatics-tools-bit). That is also conda installable, and then using the program `bit-dl-ncbi-assembly` within that toolkit, you could download all the protein sequences ahead of time by providing a file with accessions just like how they would be given to GToTree, then you can provide them to GToTree and run it without internet.
