### ISSUE TITLE
Can I build my own HMM file of Single Copy Genes for Eukaryotes using cDNA? 

### ISSUE THREAD

**Issue by ardy20** [AstrobioMike/GToTree#17]
Dear Developer

I would like to develop a HMM file including my own set of singe copy genes for a plant species to be used in GToTree for phylogenomics studies. 

However, the genome of my plant has just been sequenced and assembled by us and not all genes and proteins are known yet.

On the other hand, there is a set of SCGs in plants (106 genes) already reported by other authors, in which the protein and cDNA sequence of genes are known and available.

Can I build my HMM file of single copy genes using cDNA? Should I use the protein/or cDNA sequence of these single copy genes (106 genes)? 

Please guide the best possible approach for plants.

Regards
Ardy

**Comment by AstrobioMike** [comment]
Hi there, Ardy! 

(Just putting the email response here too in case others come with a similar question)

GToTree is designed to only work with proteins currently, so to be used with GToTree, the HMMs for the 106 genes would need to be made from the protein sequences.

If these 106 genes have PFams associated with them (or some other database that also holds HMMs), this will be very straightforward. If you have to make the individual HMM yourself for each of the 106 genes, this will involve for each individual single-copy gene: needing multiple copies of it to build its HMM; and then establishIng the cutoff thresholds for accepting a match to it. I don’t know of an automated way to do this yet unfortunately. I can’t help build it with you right now, but if you pursue this, I am happy to try to help with specific questions along the way if wanted (either through email or here).
