### ISSUE TITLE
Pipeline does not fail when bad input files are provided

### ISSUE THREAD

**Issue by jmtsuji** [AstrobioMike/GToTree#2]
Hello @AstrobioMike 

Thanks for the helpful tool. I tried running GToTree but did not initially realize that it required unzipped FastA nucleotide files as input. I tried unzipped FastA amino acid files at first, as well as gzipped FastA nucleotide files.

In both runs, GToTree ran through several steps of the pipeline before failing with a cryptic error message.

I was able to diagnose the problem, solve it, and then run GToTree successfully without issue. However, I am concerned that the current settings of GToTree do not cause the pipeline to fail when an error occurs in an individual step (e.g., prodigal). Is it possible to add try-catch statements or [`set -e`](https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/) to the code to ensure that errors of individual steps result in the program terminating?

Please let me know if you need any clarification. Again, thanks for this neat tool for automated whole genome phylogeny.

**Comment by jmtsuji** [comment]
P.S. I am using GToTree v1.1.5 on Linux (Ubuntu 18.04).

**Comment by AstrobioMike** [comment]
Hi there, Jackson!

Thanks so much for these suggested (and much needed) improvements! I really appreciate it. I will implement them ASAP and let you know when they’re in :)

I’m also working through a major overhaul where things are implemented entirely in python and controlled by snakemake, which will drastically improve things, but that’s gonna take me some time...

**Comment by jmtsuji** [comment]
Hi @AstrobioMike ,

Sounds good, and thanks for the quick response. I agree that moving to a Snakemake workflow longer-term would also address this issue.

**Comment by AstrobioMike** [comment]
Thanks again for these notes, @jmtsuji. Now from v1.1.9+, input fasta files or genbank files can be provided as gzipped or not and will be handled appropriately. Some are included as examples in the `test_data` directory example-run now that comes with the program. 

I toyed with `set -e`, and have before, but i rely on some things that make that exit when i don't want it to. For now i put in checks that should catch if an input fasta or genbank file is uninterpretable, exit the program at that point if so, and tell the user which specific file caused the problem. Not perfect still, but way better than what would have happened before like you ran into :)

I didn't yet integrate a way to provide amino acid sequences as input as the start, but I opened a new [issue](https://github.com/AstrobioMike/GToTree/issues/4) for that until i get it implemented. 

Thanks again!

**Comment by AstrobioMike** [comment]
Added in amino-acid functionality now. It's in there as of version 1.1.10+ :) Same deal as with the genbank or nucleotide fasta files, the paths to the amino acid files (one per input genome) should be specified in a single-column text file and passed to the `-A` flag of the call to the program. And of course they can also be gzipped or not now, and a couple are included with the `test_data` directory example-run :)

**Comment by jmtsuji** [comment]
@AstrobioMike Excellent -- thanks for implementing these changes so quickly!

One thing I've tried before is to toggle `set -e` on or off throughout the script (i.e., via `set +e`) so that the default behaviour is to exit out after a step produces an error (`set -e`), unless you specifically want the step to be able to fail (`set +e`). You don't necessarily have to do this, but it could provide some peace of mind about unexpected, silent errors where you don't have time to write a proper try-catch statement.

**Comment by AstrobioMike** [comment]
Oh awesome! I didn’t know about that :) I’ll mess with that next time I work on this. Thanks again!
