### ISSUE TITLE
Use labels for accession numbers

### ISSUE THREAD

**Issue by sarah872** [AstrobioMike/GToTree#21]
Hi,
I have >5000 genomes provided as a list of accession numbers and 11 genomes as genbank files. I would like to modify the labels for the genomes from accession numbers to custom labels using the `-m` parameter.
This is how I run `GToTree`:
```
GToTree -a /scratch/phylogeny/bac120_taxonomy_r95.tsv.Gamma+Zeta.acc-no.txt \
               -g /scratch/phylogeny/genbank-files.txt \
               -H Universal \
               -L Genus,Species,Strain \
               -j 8 \
               -o Gamma_labelled \
               -m /scratch/phylogeny/labels.txt \
               -t
```

But I am getting the following error:

```
               GToTree v1.4.12 (github.com/AstrobioMike/GToTree)


 ---------------------------------  RUN INFO  ---------------------------------


    Input genome sources include:
      - NCBI accessions listed in /scratch/phylogeny/bac120_taxonomy_r95.tsv.Gamma+Zeta.acc-no.txt (5802 genomes)
      - Genbank files listed in /scratch/phylogeny/genbank-files.txt (11 genomes)

                             Total input genomes: 5813

    HMM source to be used:
      - Universal_Hug_et_al (15 targets)


    Options set:
      - The output directory has been set to "Gamma_labelled/".
      - The file "/scratch/phylogeny/labels.txt" will be used to modify labels of the specified genomes.
      - Taxonkit will be used to add lineage info to labels.
      - Lineage information added to labels will be Genus, Species, Strain.
      - Number of jobs to run during parallelizable steps has been set to 8.

mv: cannot stat ‘uniq_pfam_targets.tmp’: No such file or directory

  5802 genome ID(s) listed in the mapping file (passed to "-m") not found in
  any of the input genomes :(

  Reported in the file "Missing_IDs.txt" for you to investigate.

Exiting for now.
```

The file `/scratch/phylogeny/bac120_taxonomy_r95.tsv.Gamma+Zeta.acc-no.txt` is exactly column 1 of `labels.txt`.

**Comment by AstrobioMike** [comment]
This is strange. Any chance you can send me the mapping file and the accessions file to MikeLee@bmsis.org so I can try to reproduce this?

**Comment by AstrobioMike** [comment]
I can't seem to reproduce this in my own permutations of things, will try again if/when you can send me your input mapping and accessions file :) Please also let me know the output from the environment you are running this in for `echo $0` and `uname -sr` (or `uname -a` if the previous doesn't work). 

I'd also be curious if you hit the same issue if using the conda installation. 

Sorry you've hit two unusual issues in your first attempted use, Sarah, that's a terrible first impression for GToTree :/

**Comment by sarah872** [comment]
I am very sorry but there was a type in my command :/
The files were not identical, so this is not a bug in GToTree.
But, I haven't really figured out from the documentation, how to get my custom labels. 

Running
```
GToTree -a acc-no.txt -g genbank-files.txt -H Universal -L Genus,Species,Strain -j 8 -o Gamma
```
* gives me the accession numbers

```
GToTree -a acc-no.txt -g genbank-files.txt -H Universal -L Genus,Species,Strain -j 8 -o Gamma -m labels.txt -t
```
* gives me the Genus,Species,Strain from the NCBI taxonomy

and 
```
GToTree -a acc-no.txt -g genbank-files.txt -H Universal -j 8 -o Gamma -m labels.txt -t
```
* gives me the full NCBI taxonomy.

Do I need the `-t` for my custom labels?

Thanks again for making GToTree!

**Comment by AstrobioMike** [comment]
That's great to hear! No apology needed, haha

Sorry things have been confusing on the labeling. The way it's designed, using a label mapping file like you are with the `-m` argument should work whether we use the `-t` flag (and then the `-L` argument to specify which ranks we want) or not. If both are used (a mapping file provided with `-m` and taxonomic info is to be added, indicated by giving the `-t` flag), anything that is in the mapping file will take precedence. 

So you don't need the `-t` for your custom labels, but it shouldn't mess up the re-labelling we are trying to do either. So your second and third attempts above _should_ have re-labeled the things in the mapping "labels.txt". Sorry if the wording [here](https://github.com/AstrobioMike/GToTree/wiki/user-guide#specify-desired-genome-labels) where i describe this is confusing. But that "labels.txt" should be a 2- or 3-column tab-delimited file where the first column has the accession (if the genomes we want to alter were input as accessions). Then the second column should hold what we want to rename it as, **if** we want to specify the full name. The 3rd column allows us to just append something, if we don't want to specify the whole thing but just want to add onto the label it would get (which might be just the accession, or it might be the lineage info if we used the `-t` flag). 

An example of providing the full label we want (giving a first and second column in the mapping file) is in this example table from the [alteromonas example](https://github.com/AstrobioMike/GToTree/wiki/example-usage#mapping-file-for-labeling-specific-genomes).

I can help you troubleshoot your case further if wanted/needed if you send me the input accessions file "acc-no.txt" and the mapping file "labels.txt" so i can look at things with you :)

**Comment by AstrobioMike** [comment]
Responded in email, but just noting here in brief too :) 

The problem was due to a space at the end of the entries in the input accessions and mapping files. As of v1.4.17, GToTree now checks for tabs and spaces in the input accessions file, and exits immediately with a message noting if they were found. And it notes to look for them specifically for any IDs reported from the mapping file as not being found in any input genome sources (as by eye these can look identical, so it's helpful giving a nudge to make sure there is no ending whitespace). 

Thanks again, Sarah, for sharing the snags you hit!

**Comment by sarah872** [comment]
success :)
with
`GToTree -a accno-no-spaces.txt -g genbank-files.txt -H Universal -j 20 -o tree -m labels-no-spaces.txt`
One last note: There are no duplicate labels allowed (which makes sense).
Thanks again!
