### ISSUE TITLE
No module named 'Bio' using conda install

### ISSUE THREAD

**Issue by fconstancias** [AstrobioMike/GToTree#26]
Hi Mike,

Thanks a lot for developping GToTree.
I have freshly installed GToTree using conda and I got the following issue:
```
Traceback (most recent call last):
  File "/homedir/constancias/.conda/envs/gtotree/bin/gtt-rename-fasta-headers", line 3, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
```
I tried to install/upgrade from the conda env unsucessfully since it is already installed.

```
(gtotree) [constancias@cc2-login pan]$ pip3 install biopython
Requirement already satisfied: biopython in /gs7k1/home/constancias/.conda/envs/gtotree/lib/python3.7/site-packages (1.78)
Requirement already satisfied: numpy in /gs7k1/home/constancias/.conda/envs/gtotree/lib/python3.7/site-packages (from biopython) (1.19.2)
(gtotree) [constancias@cc2-login pan]$ pip3 install biopython  --upgrade
Requirement already up-to-date: biopython in /gs7k1/home/constancias/.conda/envs/gtotree/lib/python3.7/site-packages (1.78)
Requirement already satisfied, skipping upgrade: numpy in /gs7k1/home/constancias/.conda/envs/gtotree/lib/python3.7/site-packages (from biopython) (1.19.2)

```
Any idea where I am wrong here?

Cheers,

Flo

**Comment by fconstancias** [comment]
solved - I had to activate python3 on the cluster
`module load system/python/3.7.3 `

Not sure why actually since I loaded the conda environment.

**Comment by AstrobioMike** [comment]
Hey there, Flo :)

Yea weird, and I still have limited experience on clusters so wouldn’t have been much help. Makes me worry about any other dependencies too though :/ Hopefully you don’t hit anything else. Glad to have the note about what solved it for you

Thanks for using GToTree :)

**Comment by fconstancias** [comment]
Thank you for developping GToTree, it is very usefull!
