### ISSUE TITLE
Fasta files specified cannot be found

### ISSUE THREAD

**Issue by MicroPat007** [AstrobioMike/GToTree#27]
Hi Mike, 
i wanted to try and use GToTree for a set of new archaeal MAGs. However, I keep getting this error message 

Input genome sources include:

      Some fasta files specified in MAGs.txt cannot be found :(

The example filepath that. GToTree is unhappy with however is working absolutely fine and my txt file looks just like your example file. This is probably the most basic and stupidest issue, but I have no clue how to make GToTree happy... :(

**Comment by MicroPat007** [comment]
thanks Mike, I did :)

**Comment by AstrobioMike** [comment]
Sorry, Pat, didn’t seem to come through. Can you try again for me? Michael.Lee0517@gmail.com

**Comment by AstrobioMike** [comment]
Just to note here, this was a case of different line endings in the input fasta list file. Good 'ole `dos2unix` solved the problem, e.g.:

```
conda install -c conda-forge dos2unix

dos2unix MAGs.txt
```

In this type of situation, it's great GToTree doesn't try to run when it would run into lots of problems later, but it's not a very informative error message to simply say it can't find the input fasta files. So going to add a check on the input files `file` type ASAP and return a more informative error message in these cases ASAP, and leaving this issue open until it's implemented.

Thanks for writing in and helping to improve things, Patricia!

**Comment by AstrobioMike** [comment]
This has *finally* been addressed, and should be handled internally automatically as of v1.6.10 👍
