### ISSUE TITLE
Universal HMM profile - missing L15 gene?

### ISSUE THREAD

**Issue by aiurco** [AstrobioMike/GToTree#30]
Hi @AstrobioMike !
Firstly, thank you for the great software! 

I run an archaeal tree using the Universal HMM profile. However, I can notice in the log that the Universal set uses 15 ribosomal proteins, whereas in the Hug et al (2016) paper they highlight 16 genes. 

```
 Input genome sources include:
      - Fasta files listed in file_names.txt (934 genomes)
      - 
                             �[0;32mTotal input genomes: 934�[0m
    HMM source to be used:
      - Universal_Hug_et_al (15 targets)
```

In Hug et al. (2013) paper they mention these 16 ribosomal proteins:

> Existing reference datasets for the 16 ribosomal proteins chosen as single-copy phylogenetic marker genes (RpL2, 3, 4, 5, 6, 14, **15**, 16, 18, 22, and 24, and RpS3, 8, 10, 17, and 19) 

However in the Hug et al. (2016) paper, the L15 protein is missing in the text, probably due to a typo : 

> The concatenated ribosomal protein alignment was constructed as described previously16. In brief, the 16 ribosomal protein data sets (ribosomal proteins L2, L3, L4, L5, L6, L14, L16, L18, L22, L24, S3, S8, S10, S17 and S19)

I was wondering whether it is a bug and if it is possible to add the L15 gene to the Universal set ?
Thank you very much!

**Comment by AstrobioMike** [comment]
Thank you, @aiurco! Your note I believe is exactly why it is missing the L15. I remember the disparity when looking for these, and thinking one or the other was a typo in Hug et al 2016 (either noting 16, when it should have been 15, or that it was missing one in the list). I thought I dug further before ending up going with the 15 listed, but I'm not remembering now ¯\_(ツ)_/¯  

I will add the L15 ASAP and let you know here when it is updated! Thanks! :) 

(also curious though, is there a reason you don't want to use the archaeal set in GToTree if treeing just archaea? I'm curious for myself and for GToTree's utilization :))

**Comment by AstrobioMike** [comment]
This is updated to include [L15](https://pfam.xfam.org/family/PF00827) in the Universal Hug set as of v1.5.47, which is conda-ready now.

Thanks again, @aiurco!

**Comment by aiurco** [comment]
So fast, thanks!

We are trying to reproduce a paper to place our MAGs into subgroups. We run both archaeal and universal set, however, we were more interested to try with universal set because we're concerned that not all archaeal SCGs represent vertical transfers.

**Comment by AstrobioMike** [comment]
Gotcha! Thanks again :)
