### ISSUE TITLE
Should i use the other Pfam_accession?

### ISSUE THREAD

**Issue by won9181** [AstrobioMike/GToTree#31]
Dear editor.
I thank you a lot for this tool and you.

When I use this tool, the Pfam genes in HMMs are limited for my research.
Therefore, should I know how to add specific Pfam accession numbers on hmm file? Or could you update the other DB, including the left 8,924 Pfam?

Best Regards,

**Comment by AstrobioMike** [comment]
Hi there, @won9181 :)

Thanks for writing in! 

I'm not totally following what you mean just yet, sorry. Are you talking about the Pfams searched to make a tree with an HMM marker-set included with GToTree, or are you referring to those used for additional pfam searching to count them in each genome?

**Comment by won9181** [comment]
Hi, thank you for the review.
I used the HMM marker-set (SGC set.). In the SGC set, a limited Pfam set was listed (https://github.com/AstrobioMike/GToTree/wiki/SCG-sets).
Honestly, I don't know to add the additional Pfam-set on this tool.

Regards,

**Comment by AstrobioMike** [comment]
Sorry, I'm still a little confused! (And sorry for your confusion if the documentation here hasn't been as helpful to you as I'd hoped!)

There are several HMM sets packages with GToTree that are listed on [that SCG page](https://github.com/AstrobioMike/GToTree/wiki/SCG-sets), and they are made based on their detection across different groups of taxa – each suitable for spanning a different level of diversity. Those are used for the tree'ing part.

That's separate from using GToTree to identify specific PFams in all input genomes as is done with the [Visualization of gene-presence/absence example](https://github.com/AstrobioMike/GToTree/wiki/example-usage#visualization-of-gene-presenceabsence-across-the-bacterial-domain). For that, it doesn't matter what PFams were filtered out on the SCG page. If we create a text file holding the target PFam IDs, as in [this part of the example](https://github.com/AstrobioMike/GToTree/wiki/example-usage#specifying-additional-target-pfams), GToTree will download that HMM from PFam and search the input genomes for it. 

Does that help?

**Comment by won9181** [comment]
I'm sorry to don't explain well my problems.

For example, I want to visualize Pfam code followed: PF16653.5, PF01276.20, and PF00278.
PF16653.5 and PF01276.20 were listed on SGC sets (https://github.com/AstrobioMike/GToTree/wiki/SCG-sets).
However, PF00278 is not listed on SGC sets.

In this way, how can I solve this case?

**Comment by AstrobioMike** [comment]
No worries, we'll eventually get on the same page :) 

It's ok if PF00278 is not in any of the SCG sets being used if we just want to see which genomes have it. We just need to create a text file that holds the PFAM IDs we are interested in, e.g. here in a file called "pfam-targets.txt":

```
cat pfam-targets.txt
PF16653.5
PF01276.20
PF00278
```

Each of the pfams in that file have their HMMs downloaded from PFam and searched for each genome (separate from what's in thehen run GToTree with `-p pfam-targets.txt` included. After the run, there will be an additional sub-directory in the output directory called "additional_pfam_search_results/" that holds all the results for that including the iToL-formatted files for coloring the tree, fasta files of the matches to each additional pfam, and a count table, e.g.:

![image](https://user-images.githubusercontent.com/13923308/109716264-7cbd0400-7b59-11eb-8af7-ea7b8306683e.png)

Is that what you're hoping to do?

**Comment by won9181** [comment]
Hello,
I downloaded HMM of PF00278 from Pfam at HMMS directory and run GToTree.
Then, "additional_pfam_search_results" folder was created. But, the test command was not proceeded. e.g.:
![image](https://user-images.githubusercontent.com/71337328/110084889-cf095980-7dd3-11eb-89a2-69d5f54cc59c.png)
![image](https://user-images.githubusercontent.com/71337328/110084904-d3ce0d80-7dd3-11eb-9d70-8dbcc1f05a71.png)
![image](https://user-images.githubusercontent.com/71337328/110084919-d6c8fe00-7dd3-11eb-9ff5-ac7f3014d24d.png)
Thank you for your answer. :) Always.

**Comment by AstrobioMike** [comment]
Sorry, I thought I had responded back to this ages ago :( 

I worry you may have given up and moved on by now, or hope it was solved for you. But i'm not entirely able to follow what you mean by "the test command was not proceeded". The images you show I can see in the terminal it says things are not found, but they appear to be present in the finder window you have there too. Did the "Additional_Pfam_hit_counts.tsv" file in the finder window pictured above not have what you wanted? I don't know where those files are (in the finder window) on the computer, or if you were in the same location at the terminal, so I don't know how to interpret the errors of file not found you were seeing in the terminal window snapshots.

Also, just to note, you didn't need to do this part "I downloaded HMM of PF00278 from Pfam at HMMS directory", as GToTree will automatically get them if they are listed in the file provided to the additional pfam targets argument (and it doesn't look for them in the HMMs directory that holds the single-copy genesets). 

Sorry again for the trouble you had! (and for not sending this response 3 weeks ago...)
