### ISSUE TITLE
[Question] Is there a way to use this with a collection of protein fasta files? 

### ISSUE THREAD

**Issue by jolespin** [AstrobioMike/GToTree#34]
I have several taxonomic groupings and the ORF calls for each of these. 

E.g.; 
taxon_1.faa
taxon_2.faa
...
taxon_n.faa

Can I use GToTree w/ these files? I do not have genomes for these as they are not bins/MAGs.

**Comment by AstrobioMike** [comment]
Hi there :)

Absolutely! You can pass a file holding the file names or paths to [the `-A` argument](https://github.com/AstrobioMike/GToTree/wiki/user-guide#amino-acid-files) 👍

**Comment by jolespin** [comment]
Ah @AstrobioMike  you are a legend!  Looking forward to saving a lot of time using this instead of my messy code from 2 years ago. 

Just to be sure, you run it per fasta file right? Not per directory like checkm.
