### ISSUE TITLE
THe newest conda installed version offer -H Archaea wrong

### ISSUE THREAD

**Issue by jianshu93** [AstrobioMike/GToTree#38]
Hello Mike,

I still have hmm file not offered after using -H Archaea and set the hmm directory variable. Any idea

Thanks,

Jianshu

**Comment by AstrobioMike** [comment]
Hi there, Jianshu :)

Sorry you're having trouble. That's odd. I don't have the same problem following a new conda installation. Can you tell me what you see when you run `gtt-hmms`? 

It should look something like this, listing the path to where the pre-packaged hmms are stored (which should be inside the conda environment directory) and then those that are there:

```
$ gtt-hmms

   The environment variable GToTree_HMM_dir is set to:
        /media/executor/mlee/miniconda3/envs/gtotree/share/gtotree/hmm_sets/

    The 15 available HMM SCG-sets here include:

	   Actinobacteria.hmm                (138 genes)
	   Alphaproteobacteria.hmm           (117 genes)
	   Archaea.hmm                        (76 genes)
	   Bacteria_and_Archaea.hmm           (25 genes)
	   Bacteria.hmm                       (74 genes)
	   Bacteroidetes.hmm                  (90 genes)
	   Betaproteobacteria.hmm            (203 genes)
	   Chlamydiae.hmm                    (286 genes)
	   Cyanobacteria.hmm                 (251 genes)
	   Epsilonproteobacteria.hmm         (260 genes)
	   Firmicutes.hmm                    (119 genes)
	   Gammaproteobacteria.hmm           (172 genes)
	   Proteobacteria.hmm                (119 genes)
	   Tenericutes.hmm                    (99 genes)
	   Universal_Hug_et_al.hmm            (16 genes)
```

**Comment by jianshu93** [comment]
exactly the same.

Jianshu

**Comment by AstrobioMike** [comment]
Hmm. What happens if you try this:

```
printf "GCA_001437625.1\nGCA_001543015.1\nGCA_000204585.1\n" > test-accs.txt
GToTree -a test-accs.txt -H Archaea -o test -j 2
```

Does it fail and say the HMM file can't be found? (Maybe I misunderstood what you meant with your initial post)

**Comment by jianshu93** [comment]
it works. I use -f for my own genomes and I got the mentioned error. I tried just now. It works after a second login. Many Thanks! this is really very useful and I love this tool. I usually do genome tree my self for several steps using exact the same tools you are using. It will save me a lot of time especially collecting genomes myself.

Thanks,

Jianshu

**Comment by AstrobioMike** [comment]
Excellent! Thanks, Jianshu!
