### ISSUE TITLE
No alignments to any genomes

### ISSUE THREAD

**Issue by SilasV123** [AstrobioMike/GToTree#39]
Hi,

I'm sure I am doing something silly but I can't work out what it is. I am trying to generate a tree for a set of MAGs and genomes using the following command:

GToTree -f /net/fs-1/projects01/SoilCyc/gtotree/HQ_MAGS_filelist.txt \
-H Universal_Hug_et_al \
-D -L Species,Strain \
-j 20 \
-o /net/fs-1/projects01/SoilCyc/gtotree/HQ_MAGS_output

In the output I get the following issue:
 
16 gene(s) either had no hits in any genome, or only multiple hits per
    genome... Just so ya know!!

followed by:

[0;31m************************** [0mREASON FOR TERMINATION [0;31m**************************[0m  
    After filtering out genes that had either 0 hits in any genome OR only
    multiple hits, no genes remained. This typically shouldn't happen unless
    maybe there were very few genes being targeted, or very few genomes. You
    can consider running GToTree in "best-hit" mode (by providing the '-B'
    flag with no arguments), which will retain genes from genomes with multiple
    hits - but keep in mind that is less conservative. This is also a good time
    to make sure nothing weird is going on.

If someone could help me spot where I am going wrong it would great.

Regards, 
Silas

**Comment by AstrobioMike** [comment]
Hey there, Silas :)

Sorry you’ve hit some trouble! It seems like that might happen if the bins aren’t high-quality, but I’m guessing they are supposed to be based on your HQ_MAGs label. Were these filtered by checkm or something similar to make sure they are good ones? And how many MAGs are included?

Also, can you attach the SCG_counts.tsv file that will be in the output directory here so we can see if there are none or too many being found of these target genes?

And lastly, if you would be ok with sharing maybe just two of these MAG fasta files privately with me, I can look at things directly. An email you can send them to is ***@***.*** if so :)
-Mike

--
Michael D. Lee, PhD
Blue Marble Space Institute of Science
NASA Ames Research Center
astrobiomike.github.io <- bioinformatics for beginners
GToTree <- phylogenomics for all
@AstrobioMike
Orcid ID: 0000-0001-7750-9145

**Comment by SilasV123** [comment]
Hi Mike, 

Yes these are HQ MAGs assessed with checkM (completedness >50% and contamination <20%). There are also some isolate genomes mixed in which we know are complete and good quality (single contig). 

I'm not sure how to attach files here but looking through SCG_hit_counts.tsv it just shows MAG names in the first column and the ribosomal protein names in the first row with nothing anywhere else, no matches. I will send the file in an email with a couple MAGs to you at the email you gave me, maybe along with the log file.

One thing to mention is that when I ran the test script it wasn't able to download the files needed for that run. Not sure if this failure to get files from online could be causing issues. I should also mention I have this running on a university cluster not on a PC.

Thanks for getting onto this so quickly for me.

Silas

**Comment by SilasV123** [comment]
I forgot to mention there are 294 MAGs (and genomes) included.

Silas

**Comment by AstrobioMike** [comment]
Just updating while closing this issue. There seemed to be some problem with how the system was loading libraries when run through slurm, as the main GToTree program was unable to load biopython (even though it was a conda install and it was there). I wasn't able to replicate it unfortunately. Silas was able to run things on a local computer so we both moved on with our lives :)
