### ISSUE TITLE
GToTree not working with files with Windows EOLs

### ISSUE THREAD

**Issue by anonymous7002** [AstrobioMike/GToTree#40]
I wanted to use PF00096 in Pfam targets file, but GToTree refused.
Then I realised that it needs a "dot suffix", like PF00096.12. It's very hard to find this suffix for a target, since they're not listed in Pfam's homepage.

**Comment by AstrobioMike** [comment]
Hey there,

I thought I had it set to pull the latest if no version was specified, I'll have to look into that. Thanks for the note :)

In the meantime, you can actually find the version number on the pfam site. They are listed on on the "curation & model" tab, where it says "Family (HMM) version". 

E.g. for the one you mentioned, on this page http://pfam.xfam.org/family/pf00096#tabview=tab6

![image](https://user-images.githubusercontent.com/13923308/129439736-1347095e-0a25-46e2-8ed6-52a01e551170.jpeg)

![image](https://user-images.githubusercontent.com/13923308/129439742-584acb00-dc7b-41bd-9947-184252b40203.jpeg)

So the current one is PF00096.28 👍

**Comment by anonymous7002** [comment]
Still not working:
```
  One of the target Pfams could not be successfully downloaded :(

. The problem child was PF00096.28
```

**Comment by anonymous7002** [comment]
It turned out that I have Windows EOLs in Pfam targets file.
I use WSL

**Comment by AstrobioMike** [comment]
Ah, good to know. I should put in a check for that on input files

If you need to convert files, you can install this in the GToTree environment:

`conda install -c conda-forge dos2unix`

Then if the file is called "accs.txt", for example:

`dos2unix accs.txt`

Would convert things

**Comment by AstrobioMike** [comment]
I've been meaning to implement an auto-fix for this, thanks for the reminder and motivation :) It should be dealt with internally now as of v1.6.10 👍 

And thanks overall for the help with improving the program thanks to the issues you reported!
