### ISSUE TITLE
Add a way to automatically overwrite the directory if current directory already present

### ISSUE THREAD

**Issue by anonymous7002** [AstrobioMike/GToTree#41]
When I run GToTree, I have to manually specify a different directory every time. It can't overwrite the directory.
I suggest some way for the program automatically overwrite it, something like:

Current directory already present. Overwrite?
Yes | No

**Comment by AstrobioMike** [comment]
You got it 👍  There is now an `-F` flag that can be added to force overwrite the output directory if it exists as of version 1.6.10.

Thanks!
