### ISSUE TITLE
fasta file has duplicate entries

### ISSUE THREAD

**Issue by ReneKat** [AstrobioMike/GToTree#44]
Hi Mike!
I'm working with GToTree for the first time and am excited about its potential, thanks so much for making this tool so user friendly!
I have some High Quality MAGs that are very fragmented. This one MAG has 1051 contigs and GToTree is giving me the error: 

> bin.006.fasta has duplicate entries, check it out and provide unique entries only.

However, all the contig id names are unique (e.g. >1 length=65672 depth=1.00x) ... so is there duplicates because GToTree only wants one sequence per genome? 

Thanks for the help!
All the Best,
René

**Comment by AstrobioMike** [comment]
Hey there, René!

Thanks for the kind words and for trying GToTree! Sorry it's giving you trouble!

It definitely isn't expecting one sequence per genome, but i suspect the problem may be the spaces in the headers. Though i'd imagine they would all have different first numbers (e.g. 1 above, but the next would be 2), so i'm not certain that's what's going on. Can you email me that fasta, bin.006.fasta, and I'll try to pin down what's going on? (can send to MikeLee@bmsis.org)

Thanks!

**Comment by AstrobioMike** [comment]
just noting for the future this issue was resolved, the snag was that we need to give GToTree a file holding the paths to our input fasta files (the `-f` argument), rather than giving it our actual fasta files 👍
