### ISSUE TITLE
An option to prevent database version check

### ISSUE THREAD

**Issue by felixeye** [AstrobioMike/GToTree#45]
Dear @AstrobioMike,

thank you for providing the research community with gtotree. It has been very helpful.
While installing gtotree via conda in a collaborative environment, I noticed that sometimes there is a database check (in gtt-get-accessions-from-GTDB and function check_stored_gtdb_up_to_date). The function tries to download the version number of the latest database and compare it to the existing then display a warning message if they are different.
My question is, is there a way to prevent this database check? I could find anything in the documentation.
Also the file can be downloaded in tmp rather than trying to write in the program's folders which not all users may not have access to.

Thank you for your help.

**Comment by AstrobioMike** [comment]
Hey there, @felixeye :)

Thanks for writing in with your suggestions/requests, and for the kind words

I definitely wasn't considering the permissions thing you mentioned. It's easy for me to overlook certain potential setups like that. That's a great idea. It tries to download it once and just save it to avoid downloading in the future, but putting it in temp and re-downloading when running the program would certainly be better than not being able to download it at all. I'll work on implementing that ASAP. Do you think it'd be good to be able to specify where to put it? Or just have it go to the system temp?

For the checking version bit, to make sure I'm on the same page, you thinking of having an option saying not to check that we have the latest one and automatically update? For cases where maybe we want to keep using the GTDB database version we were previously using? 

Thanks again for your input!

**Comment by felixeye** [comment]
Thank you for your quick answer @AstrobioMike,
regarding the version check, that's exactly what I meant, an option like skip_version_check. As you said if users want to fix a specific version of the DB or no internet access or any other issues that prevents writing file or downloading file.

I think having the possibility to precise the location where the file would be placed is THE BEST SOLUTION :-) and the default could be the system temp.

Let me know if you need any input from me, I would be more than happy to elaborate a bit more.

Thank you for considering the suggestion.

**Comment by AstrobioMike** [comment]
Heya, @felixeye :)

As of version 1.6.20, I've incorporated a flag to prevent the GTDB database version check, by adding the flag "--do-not-check-GTDB-version", e.g.:

```bash
gtt-get-accessions-from-GTDB -t Archaea --GTDB-representatives-only --do-not-check-GTDB-version
```

And added a flag to tell it to put the GTDB metadata in the current working directory, e.g.:

```bash
gtt-get-accessions-from-GTDB -t Archaea --GTDB-representatives-only --store-GTDB-metadata-in-current-working-dir
```

Rather than putting in in the primary GToTree data location.

I haven't been able to integrate being able to set our own storage location for data files GToTree depends on yet, as there are quite a few beyond the GTDB database, and how it's currently set up is tied to how the conda installation works. So it's going to take me a bit of time when I can sort through all of it

But wanted to update you on these in case it's helpful/needed. 

cheers :)

**Comment by felixeye** [comment]
Thank you so much @AstrobioMike for the heads up and for integrating those changes so fast.
I will test it soon and come back to you if needed.

Cheers

**Comment by AstrobioMike** [comment]
There's a whole new infrastructure for handling stored data locations as of v1.6.31, @felixeye, intended to be fully functional even when we don't have write permissions in the installed conda area :) 

Things are handled by the `gtt-data-locations` program. Thanks again for the suggestions on improving this!
