### ISSUE TITLE
Error message "-G needs to be between 0-1" whatever value I specify 

### ISSUE THREAD

**Issue by SamLambrechtsUGent** [AstrobioMike/GToTree#5]
Hi AstrobioMike, 

Thank you for the interesting tool. When I run  

`GToTree -a GToTree_ToL_accessions_29_03_19 -f fasta_files.txt -H Universal_Hug_et_al.hmm -t -j 10 -G 0.4 -o ToL_3binners_c50_x10
 `
I keep getting the following error message no matter what value I specify for `-G`
```
GToTree v1.1.10 (github.com/AstrobioMike/GToTree)

/home/sjalambr/GToTree-1.1.10/bin/GToTree: line 201: bc: command not found
/home/sjalambr/GToTree-1.1.10/bin/GToTree: line 218: bc: command not found
/home/sjalambr/GToTree-1.1.10/bin/GToTree: line 220: [: too many arguments

  The minimum genome gene-copy proportion ("-G") needs to be between 0-1.
```
Any idea what is causing this or what I did wrong? 

For your information I installed using conda as you suggested on the wiki.

Cheers,

Sam

**Comment by AstrobioMike** [comment]
Hey Sam!

Thanks very much for submitting this, and sorry for the problem. It seems I was wrong in assuming the program 'bc' (which does calculations at the command line) would be on all systems. To try to fix this for you now, in the gtotree conda environment, can you run `conda install bc` and then try again and let me know? 

If this fixes it, I will add that to the conda-setup.sh script so people won't hit the same issue in the future. 

For my curiosity, can you also please run `echo $0` to see which type of shell you are on, and if it comes back as bash, can you run `bash --version` and let me know the output? 

Thanks again!

**Comment by AstrobioMike** [comment]
Just cause it can't hurt, i've added the `bc` program to the [actual conda installation](https://github.com/AstrobioMike/GToTree/wiki/installation#conda-quickstart) as of conda version 1.4.7 build 1 (gtotree-1.4.7-py37_1), called with: 

```
conda create -y -n gtotree -c conda-forge -c bioconda -c astrobiomike gtotree
```

Thanks for letting me know this could pop up – even if it's extremely rare for a system to not have `bc` :)
