### ISSUE TITLE
Trimal shows errors when prodigal amino acid file is provided to GToTree

### ISSUE THREAD

**Issue by brymerr921** [AstrobioMike/GToTree#58]
Hi, I noticed that when I run Prodigal v2.6.3 on several genomes like this:
```
prodigal -a genome.faa -i genome.fna
```
and then feed those genomes to GToTree v1.6.34 like this:
```
GToTree -A genome_list_faa.txt -o output_faa -n 1 -j 14 -H Bacteria
```

then when `trimal` this error gets printed to the terminal thousands of times:
```
Error: the symbol '*' is incorrect
```
which makes the terminal display during the process somewhat unusable.  

If this trimal error can be safely ignored, could you consider adding ` &> /dev/null` to the end of these lines?
https://github.com/AstrobioMike/GToTree/blob/eb3aa38b6c715a2684d022a4ba0a191bd672ff2a/bin/gtt-align-and-trim-parallel.sh#L23
https://github.com/AstrobioMike/GToTree/blob/bbaec5893342e0581ce6ecaf079f9125b93f1d29/bin/GToTree#L2312

If this is an important error, is there something I should be doing differently with the FAA files? This error doesn't show up when I provide contig nucleotide sequences to GToTree.

Thank you!
Bryan

**Comment by AstrobioMike** [comment]
Hey there, Bryan :) 

Thanks for the suggestion and finding the spots! I don't know if it can be ignored, and i don't want to block out any potential output from trimal. But here's one path through this 

Prodigal includes the "*" for stop codons, and lots of other programs won't like those. GToTree gets rid of them after prodigal before giving them to trimal. This can be done like so for your example:

```bash
tr -d '*' < genome.faa > genome-clean.faa
```

Which is virtually instantaneous

An example of where this is in GToTree can be seen here:
https://github.com/AstrobioMike/GToTree/blob/eb3aa38b6c715a2684d022a4ba0a191bd672ff2a/bin/gtt-fasta-parallel.sh#L58

Will that let you get the job done?

I should put in a check for these in user-provided amino acids though, so thanks for the post :)
