### ISSUE TITLE
restarting GToTree

### ISSUE THREAD

**Issue by nicholascdove** [AstrobioMike/GToTree#60]
Hi Mike,

Thanks for the great package. Is there a way to restart an aborted GToTree run? My code stopped after `Working on Genomes provides as fasta files`. Not sure why. Maybe the last line here is relevant?

```
     Genome: AIM475966_proj1_run161_20200508_plate5006_H5_seq95405_asm98315
             Found 14 of the targeted 16 genes.
             Est. % comp: 87.50; Est. % redund: 0.00

/opt/conda/envs/gtotree/bin/gtt-fasta-parallel.sh: line 28: file: command not found
```

Either way, it would be great to pick up where I left off.

Thanks!

Nicholas

**Comment by AstrobioMike** [comment]
I found what i was initially trying to find anyway, which was a way to include that program with the conda installation to no longer rely on it being on the system as was the case up until now. (As might be expected, it can be tricky to find a program called `file`, haha)

I have this updated in conda, so if you remove the previous gtotree environment, e.g.

```bash
conda env remove -n gtotree
```

And create a new one, i *think* that will prevent that problem from happening to you again. Just installing the regular conda way _should_ grab the latest version and build, but to be sure, you can run the environment creation like this specifying explicitly to grab the latest build that includes this change (it's the same version, 1.6.35): 

```bash
create -n gtotree -c conda-forge -c bioconda -c defaults -c astrobiomike gtotree=1.6.35=py39_1
```

You could still check that `file -v` in the original environment comes up 'command not found', and then after creating and activating the new environment, checking `file -v` should tell you where it's located. Then i'd try your run again

Sorry for the trouble! Please let me know if this solves it for you. Even if not, things are a little more robust now I think with this added 👍

**Comment by nicholascdove** [comment]
Thanks Mike! Also, thanks for the fast reply! Unfortunately, I'm just now getting back to this.

I am running into a new issue (I'm happy to open another issue if you think that's best). I'm not able to set `gtt-data-locations`.  When I run `gtt-data-locations check`, I get 

> The environment variable 'GToTree_HMM_dir' does not seem to be set
>   :(
>   Try to set it with `gtt-data-locations set`.

I then run `gtt-data-locations set`, put in my paths (e.g., `/Users/ndove/opt/miniconda3/envs/gtotree/share/gtotree/hmm_sets/`), deactivate the environment and activate the environment again.

To check my work, I run `gtt-data-locations check` again, and I get the same output as before.

Any thoughts on what's going on?

**Comment by AstrobioMike** [comment]
heya, Nicholas!

Sorry you're hitting another issue :/ 

I'm kind of clueless as to guessing/figuring out what's going on with this. I can't seem to recreate the problem from fresh installs on mac or linux (only systems i have access to for testing).

Can you try doing a fresh install, replacing that last environment, and make sure it's a problem still? E.g., by running this (or replacing "conda" with "mamba" to do things faster, if you have [mamba](https://astrobiomike.github.io/unix/conda-intro#bonus-mamba-no-5) installed):

```bash
conda env remove -n gtotree
conda create -y -n gtotree -c conda-forge -c bioconda -c defaults -c astrobiomike gtotree=1.6.37
```

Then for me, running the db check right away gives me this output:

```bash
conda activate gtotree

gtt-data-locations check

#     GToTree environment variables are set as follows:
# 
# 	  variable             path
# 	  GToTree_HMM_dir      /home/mike/miniconda3/envs/gtotree/share/gtotree/hmm_sets/
# 	  TAXONKIT_DB          /home/mike/miniconda3/envs/gtotree/share/gtotree/ncbi_tax_info/
# 	  GTDB_dir             /home/mike/miniconda3/envs/gtotree/share/gtotree/gtdb_tax_info/
# 	  KO_data_dir          /home/mike/miniconda3/envs/gtotree/share/gtotree/kofamscan_data/
```

**Comment by AstrobioMike** [comment]
closing this, feel free to re-open if still having problems :)
