### ISSUE TITLE
Is this tool suitable for rodents?

### ISSUE THREAD

**Issue by kuangzhuoran** [AstrobioMike/GToTree#61]
XX

**Comment by AstrobioMike** [comment]
heya, @kuangzhuoran. I'm so sorry i didn't see this sooner, my email starting sending my github issues to spam and I was clueless about it until now :( 

I'm sure you moved on by now, but I have my thoughts about this in the wiki here: https://github.com/AstrobioMike/GToTree/wiki/things-to-consider#are-eukaryotic-genomes-appropriate-for-use-with-gtotree

Sorry again for the ridiculously slow response!
