### ISSUE TITLE
Install errors with fish shell.

### ISSUE THREAD

**Issue by vinisalazar** [AstrobioMike/GToTree#7]
Dear @AstrobioMike,

I was installing your program and bumped into a couple of (easy to fix) errors. Nevertheless, I thought you would appreciate me reporting them.

The reason I got this is because I'm using fish shell. So maybe putting a heads-up for your users to use 'normal' bash might prevent them from running into the same errors.

1. When I run `. ./conda-setup.sh` I got this error:

```
./conda-setup.sh (line 32): Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
source activate gtotree 2> /dev/null || conda activate gtotree
                                      ^
from sourcing file ./conda-setup.sh
	called on line 230 of file /usr/local/Cellar/fish/2.7.1/share/fish/config.fish

in function '.'
	called on standard input

source: Error while reading file './conda-setup.sh'
```

This was fixed simply by running `bash conda-setup.sh`, even if I was still using fish.

2. After installation, fish doesn't recognize the `gtt-hmms` command. After exiting fish, the command ran smoothly on bash.

Best,

V

**Comment by AstrobioMike** [comment]
Hi there, Vini,

Thanks so much for sending this in. I of course am trying to make things as portable as possible across all types of unix variants, but do not have the expertise to sufficiently do so, ha. I added a specific note about the fish shell at the top of the [install page on the wiki](https://github.com/AstrobioMike/GToTree/wiki/Installation).

Thanks again for taking the time to post this! It's appreciated :) 
-mike
