### ISSUE TITLE
wiki fix

### ISSUE THREAD

**Issue by hyphaltip** [AstrobioMike/GToTree#79]
on https://github.com/AstrobioMike/GToTree/wiki/SCG-sets

The text:
More information on each is provided in the "hmm_sources_and_info.tsv" file found [here](https://github.com/AstrobioMike/GToTree/blob/master/hmm_sets/hmm_sources_and_info.tsv), and in the GToTree installed location (can see by running gtt-hmms).

Needs to be corrected to (you used dashes not underscores in your file name).
More information on each is provided in the "hmm-sources-and-info.tsv" file found [here](https://github.com/AstrobioMike/GToTree/blob/master/hmm_sets/hmm-sources-and-info.tsv), and in the GToTree installed location (can see by running gtt-hmms).

I cannot see a way to clone and edit the wiki - the link for cloning the wiki is not working on the main site. This is both the text in the quotes but also the URL is broken (but will be hidden in the markdown rendering)

**Comment by AstrobioMike** [comment]
beautiful, thanks for the note! fixed! (i always wondered about editing/making suggestions on wikis too...)
