### ISSUE TITLE
pfamA.txt.gz missing from ftp?

### ISSUE THREAD

**Issue by SandersonHaley** [AstrobioMike/GToTree#84]
Hi, I am trying to get the Pfam from ftp to set up the Bacteria.hmm file for gtotree and got this output:

--2024-02-09 16:29:36--  ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/database_files/pfamA.txt.gz
           => ‘pfamA.txt.gz’
Resolving ftp.ebi.ac.uk (ftp.ebi.ac.uk)... 193.62.193.165
Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.193.165|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/databases/Pfam/releases/Pfam32.0/database_files ... 
No such directory ‘pub/databases/Pfam/releases/Pfam32.0/database_files’.

Has the file been renamed or moved?

**Comment by AstrobioMike** [comment]
Hi there :) 

Hmm, it does seem the "database_files/" directory is missing from the [Pfam32.0 directory](https://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/) currently :/ I don't host or have anything to do with Pfam or Interpro though, so i can't speak to why or where it went. 

It does exist for [Pfam33.0](https://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam33.0/) though, at https://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam33.0/database_files/pfamA.txt.gz. And up to the latest release of [Pfam36.0](https://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam36.0/), at https://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam36.0/database_files/pfamA.txt.gz

So you could try doing the process with a new version (being sure to use the same version of Pfam-A.hmm.gz too of course, but i can't say for sure all the [code from my initial building from Pfam32.0 years ago](https://github.com/AstrobioMike/GToTree/wiki/SCG-sets#code) would work the same if anything changed in the formatting (assuming that's what you were looking at when you came across this issue).

But also, just to be sure, you don't need to create that, as it (and others) are available through GToTree (you can see them all by running `gtt-hmms`) – unless of course you're trying to re-build it for yourself for another reason :)

**Comment by SandersonHaley** [comment]
Thanks, I found the files for Pfam 36.0.
