### ISSUE TITLE
Problem downloading hmm files

### ISSUE THREAD

**Issue by DBrache** [AstrobioMike/GToTree#97]
Hello, 

I keep getting this error during the test run: 
      - NCBI accessions listed in GToTree-test-data/ncbi_accessions.txt (8 genomes)
      - Genbank files listed in GToTree-test-data/genbank_files.txt (2 genomes)
      - Fasta files listed in GToTree-test-data/fasta_files.txt (2 genomes)
      - Amino-acid files listed in GToTree-test-data/amino_acid_files.txt (2 genomes)

                             Total input genomes: 14

    HMM source to be used:

      There seems to have been a problem downloading the Universal_Hug_et_al.hmm file :(
      Please try again, and if problems continue, please report an issue here:
              https://github.com/AstrobioMike/GToTree/issues

I have: 
Verified the HMM File Presence and added the path to my bashrc. 

I'm out of ideas.

FYI, I am a newbie to bioinformatics and am working on a HPC that has many limitations.

**Comment by AstrobioMike** [comment]
Hey there :) 

Sorry it's giving you trouble, and sorry you're having to learn and do things on an HPC! That definitely adds an extra layer of complication to things sometimes – i feel for you, ha

And yea that seems strange, I have at least confirmed the hmm download and full test is working for me on linux and mac still.

When you say you verified the HMM file presence, do you mean you checked for it where GToTree expects it to be under the GToTree_HMM_dir variable? Meaning if you run `ls -l ${GToTree_HMM_dir}` in the active conda environment, can you see the Universal_Hug_et_al.hmm file there?

And if you run `wc -l ${GToTree_HMM_dir}/Universal_Hug_et_al.hmm`, does it print out 6542 lines?

**Comment by DBrache** [comment]
Thank you fore your speedy response. After troubleshooting all day I took everything out and re-installed and it works fine. Issue was probably on my end with installation.
